ReportExporter sample
Genetec/DAP pull request #2
Opened 2024-05-12 06:24 UTC by alafleur-genetec

2024-05-20 02:55 UTC, dcraciunas commented on ReportExporterSample/Program.cs
> +            const string password = "Rodenbach_1516";
Remove password :)

2024-05-20 03:02 UTC, dcraciunas requested changes
Required: Remove password from samples (see comment)
Note this sample may also deserve a quick readme file to describe scope, it is clear to me from code but an external user may use some guidance on scope.

2024-05-20 08:10 UTC, alafleur-genetec commented on ReportExporterSample/Program.cs
> +            const string password = "Rodenbach_1516";
Good catch

2024-05-21 23:54 UTC, dcraciunas approved these changes

2024-05-28 22:25 UTC, merged